### ISSUE TITLE
Use pathnames instead of strings

### ISSUE THREAD

**Issue by collimarco** [SymmetricInfinity/push_package#11]
Hello, thanks for the gem!

v. 0.3.0

I've spent all the morning figuring out what was causing a bug on line 101 (in `manifest_data`) saying that the icon file doesn't exist. This was caused by `Dir.glob(@iconset_path + '/*.png')` (in `save`). Indeed if you pass a `Pathname` as the `iconset_path` (in `initialize`) instead of a string that instruction doesn't work as expected: `@iconset_path + '/*.png'` produces  `'/*.png'` which is obviously wrong.

**Comment by adamvduke** [comment]
Hey @collimarco,

Rather than making a breaking change and switching to Pathname as a requirement, we made a small change today to support accepting a Pathname as well as a string. I pushed a new version with the change if you'd like to try it. https://rubygems.org/gems/push_package/versions/0.4.0

Thanks for the feedback!
